### ISSUE TITLE
how specifically to write `info` files?

### ISSUE THREAD

**Issue by Amar1729** [ctfs/write-ups-tools#16]
Sorry, having a bit of trouble using this script to generate a skeleton for the NCL ctfs, just curious on the specifics of it. Where exactly do I specify task names, files, etc? Is the script expecting  a ctftime link (there isn't one for NCL) or `info` files at each level of a skeleton that I prefill before running `genctf.py`?

**Comment by ghost** [comment]
The `genctf` script doesn't generate the file tree for a CTF event and its challenges.

Instead create a root folder for the CTF, folders for each category, and folders for each challenge. In those folders add challenge files (that come with the challenge), and the info file. The info file then contains **just the challenge's description**. The script takes your structures and info files and creates all the README files.

An explanation is on the wiki page [**CTF Generation**](https://github.com/ctfs/write-ups-tools/wiki/CTF-Generation) now.

**Comment by Amar1729** [comment]
Awesome. Thanks for the clarifications!
